import{a as w,S as b,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const P="50629766-ca4e4f15305d377d5e3228fef",S="https://pixabay.com/api/";async function f(o,r=1,t=15){const a={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await w.get(S,{params:a})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const q=new b(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery"),m=document.querySelector(".loader"),l=document.querySelector(".load-button");function g(o){const r=o.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t.likes}</span></p>
                <p class="text">Views <span class="span">${t.views}</span></p>
                <p class="text">Comments <span class="span">${t.comments}</span></p>
                <p class="text">Downloads <span class="span">${t.downloads}</span></p>
            </div>
        </li>`).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function v(){y.innerHTML=""}function h(){m.style.display="block"}function L(){m.style.display="none"}function c(){l.classList.add("hidden")}function x(){l.classList.remove("hidden"),l.disabled=!1,l.textContent="Load more"}const $=document.querySelector(".form"),B=document.querySelector(".load-button");let n=1,d=15,p="";$.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.warning({title:"warning",message:"Please enter a search term",position:"topLeft"});return}p=r,n=1,v(),h(),c();try{const t=await f(p,n,d),{hits:a}=t;a.length===0?(c(),i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"})):(g(a),x());const e=Math.ceil(t.totalHits/d);n>=e&&c()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L()}});B.addEventListener("click",async()=>{n+=1,h();try{const o=await f(p,n,d);g(o.hits);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const t=Math.ceil(o.totalHits/d);n>=t&&(c(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L()}});
//# sourceMappingURL=index.js.map
