import{a as w,S as b,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const P="50629766-ca4e4f15305d377d5e3228fef",S="https://pixabay.com/api/";async function f(o,r=1,t=15){const a={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await w.get(S,{params:a})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const q=new b(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery"),m=document.querySelector(".loader");function g(o){const r=o.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t.likes}</span></p>
                <p class="text">Views <span class="span">${t.views}</span></p>
                <p class="text">Comments <span class="span">${t.comments}</span></p>
                <p class="text">Downloads <span class="span">${t.downloads}</span></p>
            </div>
        </li>`).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function v(){y.innerHTML=""}function h(){m.style.display="block"}function L(){m.style.display="none"}const x=document.querySelector(".form"),p=document.querySelector(".load-button");document.querySelector(".gallery");let n=1,l=15,u="";function d(){p.classList.add("hidden")}function B(){p.classList.remove("hidden")}x.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.warning({title:"warning",message:"Please enter a search term",position:"topLeft"});return}u=r,n=1,v(),h(),d();try{const t=await f(u,n,l),{hits:a}=t;a.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"}):(g(a),B());const e=Math.ceil(t.totalHits/l);n>=e&&d()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L()}});p.addEventListener("click",async()=>{n+=1,h();try{const o=await f(u,n,l);g(o.hits);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const t=Math.ceil(o.totalHits/l);n>=t&&(hideLoadButton(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L()}});
//# sourceMappingURL=index.js.map
