import{a as p,S as u,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="50629766-ca4e4f15305d377d5e3228fef",d="https://pixabay.com/api/";async function y(o,s=1,t=15){const a={key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t};try{return(await p.get(d,{params:a})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const m=new u(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".gallery"),c=document.querySelector(".loader");function g(o){const s=o.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t.likes}</span></p>
                <p class="text">Views <span class="span">${t.views}</span></p>
                <p class="text">Comments <span class="span">${t.comments}</span></p>
                <p class="text">Downloads <span class="span">${t.downloads}</span></p>
            </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",s),m.refresh()}function h(){l.innerHTML=""}function w(){c.style.display="block"}function L(){c.style.display="none"}const b=document.querySelector(".form");document.querySelector(".gallery");b.addEventListener("submit",o=>{o.preventDefault();const s=o.target.elements["search-text"].value.trim();if(!s){i.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}h(),w(),y(s).then(t=>{const{hits:a}=t;a.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):g(a)}).catch(t=>{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{L()})});
//# sourceMappingURL=index.js.map
